### PR TITLE
Fixed footer images

### PR DESCRIPTION
**Pull request by ps9793**
Hey,
I added the images for the footer icons
The bit.ly links were redirecting to a page instead of the actual image, hence the images were not being rendered on the page

### CODE REVIEW

**Comment by ps9793** [comment]
Hey Suyash,
Could you please add the hacktoberfest topic to your repository and label this pull request as hacktoberfest-accepted after you review it.
That would be really helpful
Thanks

**Comment by iamsuyashpatel07** [comment]
Okay!Thank for your conrtribution.

**Comment by iamsuyashpatel07** [comment]
Check your hacktoberfest profile and let me know that this repo is added  or not in your fest profile.

**Comment by ps9793** [comment]
The repo has been added to my profile
Thanks

**Pull request merged**
