### PR TITLE
changes on photography and portfolio section

### PR DESCRIPTION
**Pull request by krishna120801**
made a carousel for photos.  By using bootstrap.

### CODE REVIEW

**Comment by krishna120801** [comment]
PR created

**Review by iamsuyashpatel07 — APPROVED** [review]
@krishna120801 thanx for contributing

**Comment by iamsuyashpatel07** [comment]
Can you add some margin so that it have good look?

**Comment by krishna120801** [comment]
Sure

**Comment by krishna120801** [comment]
Ok I'll do it.

**Pull request merged**
